### ISSUE TITLE
Captive Portal on iOS does not open

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#22]
On my test, the browser did not open, on the latest build.

Wondering why, because on basic piratebox, it worked.

Any clues and tests welcome

**Comment by Miyitus** [comment]
yessss ill do it rn!Enviado desde mi Huawei-------- Mensaje original --------Asunto: [miyovanstenis/the.wrong] Captive Portal on iOS does not open (#22)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Subscribed On my test, the browser did not open, on the latest build.
Wondering why, because on basic piratebox, it worked.
Any clues and tests welcome

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miyovanstenis/the.wrong/issues/22?email_source=notifications\u0026email_token=AAIWQ666QXOCQK3YBM4YUSTPY5T23A5CNFSM4HTRXHS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GXWLZGA",
"url": "https://github.com/miyovanstenis/the.wrong/issues/22?email_source=notifications\u0026email_token=AAIWQ666QXOCQK3YBM4YUSTPY5T23A5CNFSM4HTRXHS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GXWLZGA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MaStr** [comment]
I found some issues on the PirateBox handling of requests toward the captive portal sent by dnsmasq.

That might have caused some issues and should help a few things
