### ISSUE TITLE
Testing the.wrong build (2019-06-20) 

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#32]
Hi,

I just created a new build, which is located at `/TheWrong/TheWrong_Builds/2019-06-20`

Solved issues:
  #31  - auto_cfg TXT files are missing
  #29 - Content update user

The txt files should be available now.
In addition, the scripts are creating a new user called `contentuser` which will be routed directly to the usb/the.wrong/ folder, which contain the files for Config and Content.

You need to setup a password for this user, like for the root user. I updated the install.sh wiki with a few notes. 

Looking forward to your feedback, if that user is ok.

best regards Matthias

**Comment by MaStr** [comment]
Please also double check if: the following things are ok & can be closed

#23 auto_flash && install time && load connection 
#26 User change the ssid 
#9 Custom Script for template
#22   Captive Portal on iOS does not open

**Comment by MaStr** [comment]
I suggest the next build will include an updated www_content folder including the new welcome.html file

**Comment by Miyitus** [comment]
Yes 9, 22 and 23 can be closedI need.ti test the new buildEnviado desde mi Huawei-------- Mensaje original --------Asunto: Re: [miyovanstenis/the.wrong] Testing the.wrong build (2019-06-20)  (#32)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Miyö Van Stenis ,Assign Please also double check if: the following things are ok & can be closed
#23 auto_flash && install time && load connection
#26 User change the ssid
#9 Custom Script for template
#22   Captive Portal on iOS does not open

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ67AUT3D35RRDVF6K5DP3MZCLA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYES2EY#issuecomment-503917843",
"url": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ67AUT3D35RRDVF6K5DP3MZCLA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYES2EY#issuecomment-503917843",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Miyitus** [comment]
Great! Thanks I'll tested todayEnviado desde mi Huawei-------- Mensaje original --------Asunto: [miyovanstenis/the.wrong] Testing the.wrong build (2019-06-20)  (#32)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Subscribed Hi,
I just created a new build, which is located at /TheWrong/TheWrong_Builds/2019-06-20
Solved issues:
#31  - auto_cfg TXT files are missing
#29 - Content update user
The txt files should be available now.
In addition, the scripts are creating a new user called contentuser which will be routed directly to the usb/the.wrong/ folder, which contain the files for Config and Content.
You need to setup a password for this user, like for the root user. I updated the install.sh wiki with a few notes.
Looking forward to your feedback, if that user is ok.
best regards Matthias

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ67K6P56547T3GB3NJTP3MYZNA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G2SXG2Q",
"url": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ67K6P56547T3GB3NJTP3MYZNA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G2SXG2Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Miyitus** [comment]
Indeed next build should be the last!!! :)Enviado desde mi Huawei-------- Mensaje original --------Asunto: Re: [miyovanstenis/the.wrong] Testing the.wrong build (2019-06-20)  (#32)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Miyö Van Stenis ,Assign I suggest the next build will include an updated www_content folder including the new welcome.html file

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ64AJW3ECMK4W5E2Y2TP3MZFBA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYES4AY#issuecomment-503918083",
"url": "https://github.com/miyovanstenis/the.wrong/issues/32?email_source=notifications\u0026email_token=AAIWQ64AJW3ECMK4W5E2Y2TP3MZFBA5CNFSM4HZQMRH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYES4AY#issuecomment-503918083",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Miyitus** [comment]
Build Tested and the config missed files are there and working so we can close:
#23 auto_flash && install time && load connection
#26 User change the ssid
#9 Custom Script for template
#22 Captive Portal on iOS does not open
